In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [3]:
dataset = [
    ["milk", "bread"],
    ["milk", "bread","egg"],
    ["milk", "egg"],
    ["bread", "bread", "butter"],
    ["bread", "butter"],
    ["milk", "bread", "egg","butter"]
]

In [5]:
te = TransactionEncoder()
te_array = te.fit_transform(dataset)

In [6]:
te_array

array([[ True, False, False,  True],
       [ True, False,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False],
       [ True,  True, False, False],
       [ True,  True,  True,  True]])

In [9]:
df = pd.DataFrame(te_array, columns = te.columns_)
df

   bread  butter    egg   milk
0   True   False  False   True
1   True   False   True   True
2  False   False   True   True
3   True    True  False  False
4   True    True  False  False
5   True    True   True   True

In [16]:
freq_items = apriori(df, min_support = 0.5, use_colnames = True)
freq_items

    support         itemsets
0  0.833333          (bread)
1  0.500000         (butter)
2  0.500000            (egg)
3  0.666667           (milk)
4  0.500000  (bread, butter)
5  0.500000    (bread, milk)
6  0.500000      (egg, milk)

In [18]:
rules = association_rules(freq_items, metric = "confidence", min_threshold = 0.4)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(bread),(butter),0.833333,0.500000,0.5,0.60,1.2,1.0,0.083333,1.250000,1.000000,0.60,0.2,0.800
1,(butter),(bread),0.500000,0.833333,0.5,1.00,1.2,1.0,0.083333,inf,0.333333,0.60,1.0,0.800
2,(bread),(milk),0.833333,0.666667,0.5,0.60,0.9,1.0,-0.055556,0.833333,-0.400000,0.50,-0.2,0.675
3,(milk),(bread),0.666667,0.833333,0.5,0.75,0.9,1.0,-0.055556,0.666667,-0.250000,0.50,-0.5,0.675
4,(egg),(milk),0.500000,0.666667,0.5,1.00,1.5,1.0,0.166667,inf,0.666667,0.75,1.0,0.875
5,(milk),(egg),0.666667,0.500000,0.5,0.75,1.5,1.0,0.166667,2.000000,1.000000,0.75,0.5,0.875